/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduledAnalysisRouteImport } from './routes/scheduled-analysis'
import { Route as ProanalysisRouteImport } from './routes/proanalysis'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProanalysisIndexRouteImport } from './routes/proanalysis.index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as SharedReportTokenRouteImport } from './routes/shared-report.$token'
import { Route as ProanalysisScheduledAnalysisRouteImport } from './routes/proanalysis.scheduled-analysis'
import { Route as AuthenticatedSupportQueriesRouteImport } from './routes/_authenticated/support-queries'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPaypalBootstrapRouteImport } from './routes/_authenticated/paypal-bootstrap'
import { Route as AuthenticatedDbTablesRouteImport } from './routes/_authenticated/db-tables'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated/datasets'
import { Route as AuthenticatedDatabaseRouteImport } from './routes/_authenticated/database'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfigurationsRouteImport } from './routes/_authenticated/configurations'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as ApiSharedTokenRouteImport } from './routes/api/shared.$token'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicSendReportEmailRouteImport } from './routes/api/public/send-report-email'
import { Route as ApiPublicSendAnalysisEmailRouteImport } from './routes/api/public/send-analysis-email'
import { Route as ApiPublicPaypalWebhookRouteImport } from './routes/api/public/paypal-webhook'
import { Route as ApiPublicCancelPaypalSubscriptionsRouteImport } from './routes/api/public/cancel-paypal-subscriptions'
import { Route as ApiPublicBackendProxyRouteImport } from './routes/api/public/backend-proxy'
import { Route as AuthenticatedReportsGeneratedRouteImport } from './routes/_authenticated/reports.generated'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports.$reportId'
import { Route as ApiPublicSharedReportTokenRouteImport } from './routes/api/public/shared-report.$token'
import { Route as ApiAnalysisAnalysisIdShareLinkRouteImport } from './routes/api/analysis.$analysisId.share-link'
import { Route as ApiAnalysisAnalysisIdShareLinkTokenRouteImport } from './routes/api/analysis.$analysisId.share-link.$token'

const ScheduledAnalysisRoute = ScheduledAnalysisRouteImport.update({
  id: '/scheduled-analysis',
  path: '/scheduled-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ProanalysisRoute = ProanalysisRouteImport.update({
  id: '/proanalysis',
  path: '/proanalysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProanalysisIndexRoute = ProanalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProanalysisRoute,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedReportTokenRoute = SharedReportTokenRouteImport.update({
  id: '/shared-report/$token',
  path: '/shared-report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProanalysisScheduledAnalysisRoute =
  ProanalysisScheduledAnalysisRouteImport.update({
    id: '/scheduled-analysis',
    path: '/scheduled-analysis',
    getParentRoute: () => ProanalysisRoute,
  } as any)
const AuthenticatedSupportQueriesRoute =
  AuthenticatedSupportQueriesRouteImport.update({
    id: '/support-queries',
    path: '/support-queries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaypalBootstrapRoute =
  AuthenticatedPaypalBootstrapRouteImport.update({
    id: '/paypal-bootstrap',
    path: '/paypal-bootstrap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDbTablesRoute = AuthenticatedDbTablesRouteImport.update({
  id: '/db-tables',
  path: '/db-tables',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatabaseRoute = AuthenticatedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigurationsRoute =
  AuthenticatedConfigurationsRouteImport.update({
    id: '/configurations',
    path: '/configurations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const ApiSharedTokenRoute = ApiSharedTokenRouteImport.update({
  id: '/api/shared/$token',
  path: '/api/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendReportEmailRoute =
  ApiPublicSendReportEmailRouteImport.update({
    id: '/api/public/send-report-email',
    path: '/api/public/send-report-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSendAnalysisEmailRoute =
  ApiPublicSendAnalysisEmailRouteImport.update({
    id: '/api/public/send-analysis-email',
    path: '/api/public/send-analysis-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaypalWebhookRoute = ApiPublicPaypalWebhookRouteImport.update({
  id: '/api/public/paypal-webhook',
  path: '/api/public/paypal-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCancelPaypalSubscriptionsRoute =
  ApiPublicCancelPaypalSubscriptionsRouteImport.update({
    id: '/api/public/cancel-paypal-subscriptions',
    path: '/api/public/cancel-paypal-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBackendProxyRoute = ApiPublicBackendProxyRouteImport.update({
  id: '/api/public/backend-proxy',
  path: '/api/public/backend-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsGeneratedRoute =
  AuthenticatedReportsGeneratedRouteImport.update({
    id: '/generated',
    path: '/generated',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const ApiPublicSharedReportTokenRoute =
  ApiPublicSharedReportTokenRouteImport.update({
    id: '/api/public/shared-report/$token',
    path: '/api/public/shared-report/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalysisAnalysisIdShareLinkRoute =
  ApiAnalysisAnalysisIdShareLinkRouteImport.update({
    id: '/api/analysis/$analysisId/share-link',
    path: '/api/analysis/$analysisId/share-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalysisAnalysisIdShareLinkTokenRoute =
  ApiAnalysisAnalysisIdShareLinkTokenRouteImport.update({
    id: '/$token',
    path: '/$token',
    getParentRoute: () => ApiAnalysisAnalysisIdShareLinkRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/logout': typeof LogoutRoute
  '/proanalysis': typeof ProanalysisRouteWithChildren
  '/scheduled-analysis': typeof ScheduledAnalysisRoute
  '/configurations': typeof AuthenticatedConfigurationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/db-tables': typeof AuthenticatedDbTablesRoute
  '/paypal-bootstrap': typeof AuthenticatedPaypalBootstrapRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/support-queries': typeof AuthenticatedSupportQueriesRoute
  '/proanalysis/scheduled-analysis': typeof ProanalysisScheduledAnalysisRoute
  '/shared-report/$token': typeof SharedReportTokenRoute
  '/shared/$token': typeof SharedTokenRoute
  '/proanalysis/': typeof ProanalysisIndexRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/reports/generated': typeof AuthenticatedReportsGeneratedRoute
  '/api/public/backend-proxy': typeof ApiPublicBackendProxyRoute
  '/api/public/cancel-paypal-subscriptions': typeof ApiPublicCancelPaypalSubscriptionsRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/send-analysis-email': typeof ApiPublicSendAnalysisEmailRoute
  '/api/public/send-report-email': typeof ApiPublicSendReportEmailRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/api/analysis/$analysisId/share-link': typeof ApiAnalysisAnalysisIdShareLinkRouteWithChildren
  '/api/public/shared-report/$token': typeof ApiPublicSharedReportTokenRoute
  '/api/analysis/$analysisId/share-link/$token': typeof ApiAnalysisAnalysisIdShareLinkTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/logout': typeof LogoutRoute
  '/scheduled-analysis': typeof ScheduledAnalysisRoute
  '/configurations': typeof AuthenticatedConfigurationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/db-tables': typeof AuthenticatedDbTablesRoute
  '/paypal-bootstrap': typeof AuthenticatedPaypalBootstrapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/support-queries': typeof AuthenticatedSupportQueriesRoute
  '/proanalysis/scheduled-analysis': typeof ProanalysisScheduledAnalysisRoute
  '/shared-report/$token': typeof SharedReportTokenRoute
  '/shared/$token': typeof SharedTokenRoute
  '/proanalysis': typeof ProanalysisIndexRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/reports/generated': typeof AuthenticatedReportsGeneratedRoute
  '/api/public/backend-proxy': typeof ApiPublicBackendProxyRoute
  '/api/public/cancel-paypal-subscriptions': typeof ApiPublicCancelPaypalSubscriptionsRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/send-analysis-email': typeof ApiPublicSendAnalysisEmailRoute
  '/api/public/send-report-email': typeof ApiPublicSendReportEmailRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/api/analysis/$analysisId/share-link': typeof ApiAnalysisAnalysisIdShareLinkRouteWithChildren
  '/api/public/shared-report/$token': typeof ApiPublicSharedReportTokenRoute
  '/api/analysis/$analysisId/share-link/$token': typeof ApiAnalysisAnalysisIdShareLinkTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/logout': typeof LogoutRoute
  '/proanalysis': typeof ProanalysisRouteWithChildren
  '/scheduled-analysis': typeof ScheduledAnalysisRoute
  '/_authenticated/configurations': typeof AuthenticatedConfigurationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/database': typeof AuthenticatedDatabaseRoute
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRoute
  '/_authenticated/db-tables': typeof AuthenticatedDbTablesRoute
  '/_authenticated/paypal-bootstrap': typeof AuthenticatedPaypalBootstrapRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/support-queries': typeof AuthenticatedSupportQueriesRoute
  '/proanalysis/scheduled-analysis': typeof ProanalysisScheduledAnalysisRoute
  '/shared-report/$token': typeof SharedReportTokenRoute
  '/shared/$token': typeof SharedTokenRoute
  '/proanalysis/': typeof ProanalysisIndexRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/_authenticated/reports/generated': typeof AuthenticatedReportsGeneratedRoute
  '/api/public/backend-proxy': typeof ApiPublicBackendProxyRoute
  '/api/public/cancel-paypal-subscriptions': typeof ApiPublicCancelPaypalSubscriptionsRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/send-analysis-email': typeof ApiPublicSendAnalysisEmailRoute
  '/api/public/send-report-email': typeof ApiPublicSendReportEmailRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/api/analysis/$analysisId/share-link': typeof ApiAnalysisAnalysisIdShareLinkRouteWithChildren
  '/api/public/shared-report/$token': typeof ApiPublicSharedReportTokenRoute
  '/api/analysis/$analysisId/share-link/$token': typeof ApiAnalysisAnalysisIdShareLinkTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/logout'
    | '/proanalysis'
    | '/scheduled-analysis'
    | '/configurations'
    | '/dashboard'
    | '/database'
    | '/datasets'
    | '/db-tables'
    | '/paypal-bootstrap'
    | '/reports'
    | '/settings'
    | '/support'
    | '/support-queries'
    | '/proanalysis/scheduled-analysis'
    | '/shared-report/$token'
    | '/shared/$token'
    | '/proanalysis/'
    | '/reports/$reportId'
    | '/reports/generated'
    | '/api/public/backend-proxy'
    | '/api/public/cancel-paypal-subscriptions'
    | '/api/public/paypal-webhook'
    | '/api/public/send-analysis-email'
    | '/api/public/send-report-email'
    | '/api/public/stripe-webhook'
    | '/api/shared/$token'
    | '/reports/'
    | '/api/analysis/$analysisId/share-link'
    | '/api/public/shared-report/$token'
    | '/api/analysis/$analysisId/share-link/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/logout'
    | '/scheduled-analysis'
    | '/configurations'
    | '/dashboard'
    | '/database'
    | '/datasets'
    | '/db-tables'
    | '/paypal-bootstrap'
    | '/settings'
    | '/support'
    | '/support-queries'
    | '/proanalysis/scheduled-analysis'
    | '/shared-report/$token'
    | '/shared/$token'
    | '/proanalysis'
    | '/reports/$reportId'
    | '/reports/generated'
    | '/api/public/backend-proxy'
    | '/api/public/cancel-paypal-subscriptions'
    | '/api/public/paypal-webhook'
    | '/api/public/send-analysis-email'
    | '/api/public/send-report-email'
    | '/api/public/stripe-webhook'
    | '/api/shared/$token'
    | '/reports'
    | '/api/analysis/$analysisId/share-link'
    | '/api/public/shared-report/$token'
    | '/api/analysis/$analysisId/share-link/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analysis'
    | '/logout'
    | '/proanalysis'
    | '/scheduled-analysis'
    | '/_authenticated/configurations'
    | '/_authenticated/dashboard'
    | '/_authenticated/database'
    | '/_authenticated/datasets'
    | '/_authenticated/db-tables'
    | '/_authenticated/paypal-bootstrap'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/support-queries'
    | '/proanalysis/scheduled-analysis'
    | '/shared-report/$token'
    | '/shared/$token'
    | '/proanalysis/'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/reports/generated'
    | '/api/public/backend-proxy'
    | '/api/public/cancel-paypal-subscriptions'
    | '/api/public/paypal-webhook'
    | '/api/public/send-analysis-email'
    | '/api/public/send-report-email'
    | '/api/public/stripe-webhook'
    | '/api/shared/$token'
    | '/_authenticated/reports/'
    | '/api/analysis/$analysisId/share-link'
    | '/api/public/shared-report/$token'
    | '/api/analysis/$analysisId/share-link/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalysisRoute: typeof AnalysisRoute
  LogoutRoute: typeof LogoutRoute
  ProanalysisRoute: typeof ProanalysisRouteWithChildren
  ScheduledAnalysisRoute: typeof ScheduledAnalysisRoute
  SharedReportTokenRoute: typeof SharedReportTokenRoute
  SharedTokenRoute: typeof SharedTokenRoute
  ApiPublicBackendProxyRoute: typeof ApiPublicBackendProxyRoute
  ApiPublicCancelPaypalSubscriptionsRoute: typeof ApiPublicCancelPaypalSubscriptionsRoute
  ApiPublicPaypalWebhookRoute: typeof ApiPublicPaypalWebhookRoute
  ApiPublicSendAnalysisEmailRoute: typeof ApiPublicSendAnalysisEmailRoute
  ApiPublicSendReportEmailRoute: typeof ApiPublicSendReportEmailRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiSharedTokenRoute: typeof ApiSharedTokenRoute
  ApiAnalysisAnalysisIdShareLinkRoute: typeof ApiAnalysisAnalysisIdShareLinkRouteWithChildren
  ApiPublicSharedReportTokenRoute: typeof ApiPublicSharedReportTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduled-analysis': {
      id: '/scheduled-analysis'
      path: '/scheduled-analysis'
      fullPath: '/scheduled-analysis'
      preLoaderRoute: typeof ScheduledAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proanalysis': {
      id: '/proanalysis'
      path: '/proanalysis'
      fullPath: '/proanalysis'
      preLoaderRoute: typeof ProanalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proanalysis/': {
      id: '/proanalysis/'
      path: '/'
      fullPath: '/proanalysis/'
      preLoaderRoute: typeof ProanalysisIndexRouteImport
      parentRoute: typeof ProanalysisRoute
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-report/$token': {
      id: '/shared-report/$token'
      path: '/shared-report/$token'
      fullPath: '/shared-report/$token'
      preLoaderRoute: typeof SharedReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proanalysis/scheduled-analysis': {
      id: '/proanalysis/scheduled-analysis'
      path: '/scheduled-analysis'
      fullPath: '/proanalysis/scheduled-analysis'
      preLoaderRoute: typeof ProanalysisScheduledAnalysisRouteImport
      parentRoute: typeof ProanalysisRoute
    }
    '/_authenticated/support-queries': {
      id: '/_authenticated/support-queries'
      path: '/support-queries'
      fullPath: '/support-queries'
      preLoaderRoute: typeof AuthenticatedSupportQueriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paypal-bootstrap': {
      id: '/_authenticated/paypal-bootstrap'
      path: '/paypal-bootstrap'
      fullPath: '/paypal-bootstrap'
      preLoaderRoute: typeof AuthenticatedPaypalBootstrapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/db-tables': {
      id: '/_authenticated/db-tables'
      path: '/db-tables'
      fullPath: '/db-tables'
      preLoaderRoute: typeof AuthenticatedDbTablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/database': {
      id: '/_authenticated/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthenticatedDatabaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configurations': {
      id: '/_authenticated/configurations'
      path: '/configurations'
      fullPath: '/configurations'
      preLoaderRoute: typeof AuthenticatedConfigurationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/api/shared/$token': {
      id: '/api/shared/$token'
      path: '/api/shared/$token'
      fullPath: '/api/shared/$token'
      preLoaderRoute: typeof ApiSharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-report-email': {
      id: '/api/public/send-report-email'
      path: '/api/public/send-report-email'
      fullPath: '/api/public/send-report-email'
      preLoaderRoute: typeof ApiPublicSendReportEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-analysis-email': {
      id: '/api/public/send-analysis-email'
      path: '/api/public/send-analysis-email'
      fullPath: '/api/public/send-analysis-email'
      preLoaderRoute: typeof ApiPublicSendAnalysisEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal-webhook': {
      id: '/api/public/paypal-webhook'
      path: '/api/public/paypal-webhook'
      fullPath: '/api/public/paypal-webhook'
      preLoaderRoute: typeof ApiPublicPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cancel-paypal-subscriptions': {
      id: '/api/public/cancel-paypal-subscriptions'
      path: '/api/public/cancel-paypal-subscriptions'
      fullPath: '/api/public/cancel-paypal-subscriptions'
      preLoaderRoute: typeof ApiPublicCancelPaypalSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backend-proxy': {
      id: '/api/public/backend-proxy'
      path: '/api/public/backend-proxy'
      fullPath: '/api/public/backend-proxy'
      preLoaderRoute: typeof ApiPublicBackendProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/generated': {
      id: '/_authenticated/reports/generated'
      path: '/generated'
      fullPath: '/reports/generated'
      preLoaderRoute: typeof AuthenticatedReportsGeneratedRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/api/public/shared-report/$token': {
      id: '/api/public/shared-report/$token'
      path: '/api/public/shared-report/$token'
      fullPath: '/api/public/shared-report/$token'
      preLoaderRoute: typeof ApiPublicSharedReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analysis/$analysisId/share-link': {
      id: '/api/analysis/$analysisId/share-link'
      path: '/api/analysis/$analysisId/share-link'
      fullPath: '/api/analysis/$analysisId/share-link'
      preLoaderRoute: typeof ApiAnalysisAnalysisIdShareLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analysis/$analysisId/share-link/$token': {
      id: '/api/analysis/$analysisId/share-link/$token'
      path: '/$token'
      fullPath: '/api/analysis/$analysisId/share-link/$token'
      preLoaderRoute: typeof ApiAnalysisAnalysisIdShareLinkTokenRouteImport
      parentRoute: typeof ApiAnalysisAnalysisIdShareLinkRoute
    }
  }
}

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
  AuthenticatedReportsGeneratedRoute: typeof AuthenticatedReportsGeneratedRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
  AuthenticatedReportsGeneratedRoute: AuthenticatedReportsGeneratedRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfigurationsRoute: typeof AuthenticatedConfigurationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatabaseRoute: typeof AuthenticatedDatabaseRoute
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRoute
  AuthenticatedDbTablesRoute: typeof AuthenticatedDbTablesRoute
  AuthenticatedPaypalBootstrapRoute: typeof AuthenticatedPaypalBootstrapRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedSupportQueriesRoute: typeof AuthenticatedSupportQueriesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfigurationsRoute: AuthenticatedConfigurationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatabaseRoute: AuthenticatedDatabaseRoute,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRoute,
  AuthenticatedDbTablesRoute: AuthenticatedDbTablesRoute,
  AuthenticatedPaypalBootstrapRoute: AuthenticatedPaypalBootstrapRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedSupportQueriesRoute: AuthenticatedSupportQueriesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProanalysisRouteChildren {
  ProanalysisScheduledAnalysisRoute: typeof ProanalysisScheduledAnalysisRoute
  ProanalysisIndexRoute: typeof ProanalysisIndexRoute
}

const ProanalysisRouteChildren: ProanalysisRouteChildren = {
  ProanalysisScheduledAnalysisRoute: ProanalysisScheduledAnalysisRoute,
  ProanalysisIndexRoute: ProanalysisIndexRoute,
}

const ProanalysisRouteWithChildren = ProanalysisRoute._addFileChildren(
  ProanalysisRouteChildren,
)

interface ApiAnalysisAnalysisIdShareLinkRouteChildren {
  ApiAnalysisAnalysisIdShareLinkTokenRoute: typeof ApiAnalysisAnalysisIdShareLinkTokenRoute
}

const ApiAnalysisAnalysisIdShareLinkRouteChildren: ApiAnalysisAnalysisIdShareLinkRouteChildren =
  {
    ApiAnalysisAnalysisIdShareLinkTokenRoute:
      ApiAnalysisAnalysisIdShareLinkTokenRoute,
  }

const ApiAnalysisAnalysisIdShareLinkRouteWithChildren =
  ApiAnalysisAnalysisIdShareLinkRoute._addFileChildren(
    ApiAnalysisAnalysisIdShareLinkRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalysisRoute: AnalysisRoute,
  LogoutRoute: LogoutRoute,
  ProanalysisRoute: ProanalysisRouteWithChildren,
  ScheduledAnalysisRoute: ScheduledAnalysisRoute,
  SharedReportTokenRoute: SharedReportTokenRoute,
  SharedTokenRoute: SharedTokenRoute,
  ApiPublicBackendProxyRoute: ApiPublicBackendProxyRoute,
  ApiPublicCancelPaypalSubscriptionsRoute:
    ApiPublicCancelPaypalSubscriptionsRoute,
  ApiPublicPaypalWebhookRoute: ApiPublicPaypalWebhookRoute,
  ApiPublicSendAnalysisEmailRoute: ApiPublicSendAnalysisEmailRoute,
  ApiPublicSendReportEmailRoute: ApiPublicSendReportEmailRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiSharedTokenRoute: ApiSharedTokenRoute,
  ApiAnalysisAnalysisIdShareLinkRoute:
    ApiAnalysisAnalysisIdShareLinkRouteWithChildren,
  ApiPublicSharedReportTokenRoute: ApiPublicSharedReportTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
