// Persistence helpers for chat turns inside an analysis.
//
// Design: one row in `analyses` per "conversation thread" on a dataset.
// One row in `analysis_messages` per user prompt or AI reply inside that
// thread. The `analysis_id` (UUID) is generated by Postgres
// (`default gen_random_uuid()`) on the first insert into `analyses`, returned
// in the same round-trip via `.select().single()`, and then placed in the
// URL so reload/share works. RLS guarantees a user only ever sees and
// writes their own analyses and messages.

import { supabase } from "@/integrations/supabase/client";
import { requireCurrentProfileId } from "@/lib/current-profile";
import { getCurrentOrgId } from "@/lib/current-org";
import { getCachedAuthUser } from "@/lib/auth-user";


export type AnalysisMessageRole = "user" | "assistant";

export type AnalysisMessage = {
  id: string;
  analysis_id: string;
  role: AnalysisMessageRole;
  content: string;
  output: unknown | null;
  author_id: string | null;
  created_at: string;
};

async function uid(): Promise<string> {
  const data = { user: await getCachedAuthUser() };
  if (!data.user) throw new Error("Not signed in");
  return data.user.id;
}

export type AnalysisContext = {
  dataset_id?: string | null;
  thread_id?: string | null;
  session_id?: string | null;
  filename?: string | null;
  schema?: unknown;
  samples?: unknown;
  viz_config?: unknown;
};

/**
 * Create a new analysis row. The database assigns `id` (UUID) — we return it
 * so the caller can put it in the URL and use it for subsequent message
 * inserts.
 */
export async function createAnalysis(
  input: {
    project_id: string | null;
    parent_analysis_id?: string | null;
    name?: string;
  } & AnalysisContext,
): Promise<{ id: string; project_id: string | null; name: string }> {
  const owner_id = await requireCurrentProfileId();
  const organization_id = await getCurrentOrgId();
  const { data, error } = await supabase
    .from("analyses")
    .insert({
      owner_id,
      organization_id,
      project_id: input.project_id,
      parent_analysis_id: input.parent_analysis_id ?? null,
      name: input.name ?? "New Analysis",
      team_label: "Team",
      team_count: 0,
      dataset_id: input.dataset_id ?? null,
      thread_id: input.thread_id ?? null,
      session_id: input.session_id ?? null,
      filename: input.filename ?? null,
      schema: input.schema ?? null,
      samples: input.samples ?? null,
      viz_config: input.viz_config ?? null,
    } as any)
    .select("id,project_id,name")
    .single();
  if (error) throw error;
  return data;
}

/** Patch dataset/thread/viz fields on an existing analysis row (best-effort). */
export async function updateAnalysisContext(id: string, patch: AnalysisContext): Promise<void> {
  const row: Record<string, unknown> = {};
  if (patch.dataset_id !== undefined) row.dataset_id = patch.dataset_id;
  if (patch.thread_id !== undefined) row.thread_id = patch.thread_id;
  if (patch.session_id !== undefined) row.session_id = patch.session_id;
  if (patch.filename !== undefined) row.filename = patch.filename;
  if (patch.schema !== undefined) row.schema = patch.schema;
  if (patch.samples !== undefined) row.samples = patch.samples;
  if (patch.viz_config !== undefined) row.viz_config = patch.viz_config;

  if (Object.keys(row).length === 0) return;
  const { error } = await supabase
    .from("analyses")
    .update(row as any)
    .eq("id", id);
  if (error) throw error;
}

/** Load the full analysis row including persisted dataset context. */
export async function loadAnalysis(id: string): Promise<
  | (AnalysisContext & {
      id: string;
      name: string;
      project_id: string | null;
    })
  | null
> {
  const { data, error } = await supabase
    .from("analyses")
    .select("id,name,project_id,parent_analysis_id,dataset_id,thread_id,session_id,filename,schema,samples,viz_config")
    .eq("id", id)
    .maybeSingle();
  if (error) throw error;
  return (data ?? null) as any;
}

export type ChildAnalysisSummary = { id: string; name: string; created_at: string };

/** Child analyses linked to a mother analysis (ordered oldest first). */
export async function loadChildAnalyses(parentAnalysisId: string): Promise<ChildAnalysisSummary[]> {
  const { data, error } = await supabase
    .from("analyses")
    .select("id,name,created_at")
    .eq("parent_analysis_id", parentAnalysisId)
    .order("created_at", { ascending: true });
  if (error) throw error;
  return (data ?? []) as ChildAnalysisSummary[];
}

export type GroupDataset = {
  analysisId: string;
  dataset_id: string;
  name: string;
  session_id: string | null;
  thread_id: string | null;
};

/**
 * Every dataset belonging to a multi-file analysis group (parent + children),
 * in upload order. Accepts any member id (parent or child).
 */
export async function loadAnalysisGroupDatasets(analysisId: string): Promise<GroupDataset[]> {
  const { data: self, error: selfErr } = await supabase
    .from("analyses")
    .select("id,name,parent_analysis_id,dataset_id,filename,session_id,thread_id,created_at")
    .eq("id", analysisId)
    .maybeSingle();
  if (selfErr) throw selfErr;
  if (!self) return [];

  const parentId = (self as any).parent_analysis_id ?? (self as any).id;

  const [{ data: parentRow }, { data: children }] = await Promise.all([
    parentId === (self as any).id
      ? Promise.resolve({ data: self as any })
      : supabase
          .from("analyses")
          .select("id,name,parent_analysis_id,dataset_id,filename,session_id,thread_id,created_at")
          .eq("id", parentId)
          .maybeSingle(),
    supabase
      .from("analyses")
      .select("id,name,parent_analysis_id,dataset_id,filename,session_id,thread_id,created_at")
      .eq("parent_analysis_id", parentId)
      .order("created_at", { ascending: true }),
  ]);

  const rows = [parentRow, ...((children ?? []) as any[])].filter(Boolean) as any[];
  const seen = new Set<string>();
  const out: GroupDataset[] = [];
  for (const r of rows) {
    if (!r?.dataset_id || seen.has(r.dataset_id)) continue;
    seen.add(r.dataset_id);
    out.push({
      analysisId: r.id,
      dataset_id: r.dataset_id,
      name: r.filename || r.name || "Dataset",
      session_id: r.session_id ?? null,
      thread_id: r.thread_id ?? null,
    });
  }
  return out;
}

/** Resolve the root (mother) analysis id for any analysis row. */
export async function resolveMotherAnalysisId(analysisId: string): Promise<string> {
  const row = await loadAnalysis(analysisId);
  if (!row) return analysisId;
  const parentId = (row as { parent_analysis_id?: string | null }).parent_analysis_id;
  return parentId ?? analysisId;
}

/**
 * Append one chat turn (user prompt OR assistant reply) to an analysis.
 * `output` is optional structured payload for the assistant (table rows,
 * chart config, etc.).
 */
export async function appendMessage(input: {
  analysis_id: string;
  role: AnalysisMessageRole;
  content: string;
  output?: unknown;
  author_id?: string | null;
}): Promise<AnalysisMessage> {
  const { data, error } = await supabase
    .from("analysis_messages")
    .insert({
      analysis_id: input.analysis_id,
      role: input.role,
      content: input.content,
      output: input.output ?? null,
      author_id: input.author_id ?? null,
    } as any)
    .select("id,analysis_id,role,content,output,author_id,created_at")
    .single();
  if (error) throw error;
  return data as AnalysisMessage;
}

/** Load all messages for an analysis in chronological order. */
export async function loadMessages(analysisId: string): Promise<AnalysisMessage[]> {
  const { data, error } = await supabase
    .from("analysis_messages")
    .select("id,analysis_id,role,content,output,author_id,created_at")
    .eq("analysis_id", analysisId)
    .order("created_at", { ascending: true });
  if (error) throw error;
  return (data ?? []) as AnalysisMessage[];
}

/** Convenience: get the user's most-recent project id, used as a fallback
 *  when the analysis page has no explicit project context. */
export async function getDefaultProjectId(): Promise<string | null> {
  const { data, error } = await supabase
    .from("projects")
    .select("id")
    .is("deleted_at", null)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (error) {
    console.warn("getDefaultProjectId select failed", error);
    return null;
  }
  if (data?.id) return data.id;

  // No project yet — create a default one so analyses can be persisted.
  const profileId = await requireCurrentProfileId().catch(() => null);
  if (!profileId) return null;
  const { data: created, error: insertErr } = await supabase
    .from("projects")
    .insert({ name: "My Project", owner_id: profileId })
    .select("id")
    .single();
  if (insertErr) {
    console.warn("getDefaultProjectId auto-create failed", insertErr);
    return null;
  }
  return created.id;
}
