"""HTML / Markdown report rendering.

Templates live as strings (rendered with Jinja2) so the package has no runtime
dependency on template-file discovery. Reports present *measured* facts; an
optional LLM only enriches the narrative summary, never the numbers.
"""

from __future__ import annotations

from typing import Any

from jinja2 import Environment

_env = Environment(autoescape=True, trim_blocks=True, lstrip_blocks=True)

_BASE_CSS = """
body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;color:#1b1f24;background:#f6f8fa}
.wrap{max-width:960px;margin:0 auto;padding:32px}
h1{font-size:28px;margin:0 0 4px} h2{font-size:20px;margin:28px 0 8px;border-bottom:1px solid #e1e4e8;padding-bottom:6px}
.sub{color:#57606a;margin:0 0 20px}
.card{background:#fff;border:1px solid #e1e4e8;border-radius:8px;padding:16px 20px;margin:14px 0}
table{border-collapse:collapse;width:100%;font-size:14px} th,td{text-align:left;padding:7px 10px;border-bottom:1px solid #eaecef}
th{background:#f6f8fa} .kpi{display:inline-block;min-width:150px;margin:6px 18px 6px 0}
.kpi .v{font-size:22px;font-weight:600} .kpi .l{color:#57606a;font-size:12px;text-transform:uppercase;letter-spacing:.04em}
.pass{color:#1a7f37;font-weight:600}.warn{color:#9a6700;font-weight:600}.fail{color:#cf222e;font-weight:600}
.badge{display:inline-block;padding:2px 8px;border-radius:12px;font-size:12px;background:#ddf4ff;color:#0969da}
.muted{color:#57606a;font-size:13px} code{background:#eff1f3;padding:1px 5px;border-radius:4px}
"""

_EXEC = """<!doctype html><html><head><meta charset="utf-8"><title>Executive report — {{ goal }}</title>
<style>{{ css }}</style></head><body><div class="wrap">
<h1>Executive report</h1>
<p class="sub">{{ goal }} &nbsp;·&nbsp; mission <code>{{ mission_id }}</code> &nbsp;·&nbsp; <span class="badge">{{ kind }}</span></p>

<div class="card">
{% for k, v in kpis %}<div class="kpi"><div class="v">{{ v }}</div><div class="l">{{ k }}</div></div>{% endfor %}
</div>

<h2>What we did</h2>
<div class="card"><p>{{ narrative }}</p></div>

<h2>Economics of this mission</h2>
<div class="card"><table><tr><th>Measure</th><th>Value</th></tr>
{% for k, v in economics %}<tr><td>{{ k }}</td><td>{{ v }}</td></tr>{% endfor %}
</table>
<p class="muted">Estimated manual effort is a conservative heuristic, to be calibrated from observed customer workflows — not an LLM guess.</p></div>

<h2>Key findings</h2>
<div class="card"><ul>{% for f in findings %}<li>{{ f }}</li>{% endfor %}</ul></div>

<h2>Validation &amp; limitations</h2>
<div class="card"><p>Validation verdict: <span class="{{ verdict }}">{{ verdict|upper }}</span>.
Maximum safe deployment level: <strong>{{ max_level }}</strong> of 4.</p>
<ul>{% for l in limitations %}<li>{{ l }}</li>{% endfor %}</ul></div>

<h2>Fireflies activated</h2>
<div class="card"><table><tr><th>Firefly</th><th>Human role</th><th>Output</th></tr>
{% for u in units %}<tr><td>{{ u.firefly }}</td><td>{{ u.human_role }}</td><td>{{ u.output }}</td></tr>{% endfor %}
</table></div>
<p class="muted">Generated by Avaloka. Reproduce or adapt this analysis with <code>avaloka</code>.</p>
</div></body></html>"""

_TECH = """<!doctype html><html><head><meta charset="utf-8"><title>Technical report — {{ goal }}</title>
<style>{{ css }}</style></head><body><div class="wrap">
<h1>Technical report</h1>
<p class="sub">{{ goal }} · mission <code>{{ mission_id }}</code></p>

<h2>Dataset</h2>
<div class="card"><p><code>{{ ds.source }}</code> — {{ ds.n_rows }} rows × {{ ds.n_cols }} cols
({{ ds.format }}). Quality score <strong>{{ quality.score }}/100</strong>.
SHA-256 <span class="muted">{{ ds.sha256[:16] }}…</span></p></div>

<h2>Schema &amp; distributions</h2>
<div class="card"><table><tr><th>Column</th><th>Role</th><th>Dtype</th><th>Missing</th><th>Unique</th><th>Summary</th></tr>
{% for c in columns %}<tr><td>{{ c.name }}</td><td>{{ c.role }}</td><td>{{ c.dtype }}</td>
<td>{{ '%.1f'|format(c.missing_pct*100) }}%</td><td>{{ c.n_unique }}</td>
<td class="muted">{% if c.stats %}μ={{ '%.3g'|format(c.stats.mean) }}, σ={{ '%.3g'|format(c.stats.std) }},
[{{ '%.3g'|format(c.stats.min) }}, {{ '%.3g'|format(c.stats.max) }}], outliers={{ c.stats.n_outliers }}
{% elif c.top_values %}top: {% for t in c.top_values[:3] %}{{ t.value }}({{ t.count }}){% if not loop.last %}, {% endif %}{% endfor %}{% endif %}</td></tr>{% endfor %}
</table></div>

{% if correlations %}<h2>Strongest correlations</h2>
<div class="card"><table><tr><th>A</th><th>B</th><th>|corr|</th></tr>
{% for p in correlations %}<tr><td>{{ p.a }}</td><td>{{ p.b }}</td><td>{{ p.corr }}</td></tr>{% endfor %}</table></div>{% endif %}

<h2>Data quality issues</h2>
<div class="card">{% if quality.issues %}<table><tr><th>Severity</th><th>Column</th><th>Issue</th></tr>
{% for i in quality.issues %}<tr><td class="{{ 'fail' if i.severity=='high' else 'warn' if i.severity=='medium' else 'muted' }}">{{ i.severity }}</td>
<td>{{ i.column or '—' }}</td><td>{{ i.detail }}</td></tr>{% endfor %}</table>
{% else %}<p>No material quality issues detected.</p>{% endif %}</div>

<h2>Plan</h2>
<div class="card"><p>Task: <strong>{{ plan.task }}</strong> — {{ plan.task_reason }}</p>
<p>Split: <code>{{ plan.split.strategy }}</code> — {{ plan.split.reason }}</p>
<p>Candidate algorithms: {{ plan.candidate_algorithms|join(', ') or '—' }}</p>
<p class="muted">{{ plan.compute_plan.budget_note }}</p>
<p><strong>Hypotheses:</strong></p><ul>{% for h in plan.hypotheses %}<li>{{ h }}</li>{% endfor %}</ul></div>

{% if model %}<h2>Model results</h2>
<div class="card"><table><tr><th>Candidate</th><th>{{ model.metric }}</th><th>CV mean ± std</th><th>Train s</th><th>Latency ms</th></tr>
{% for c in model.candidates %}<tr {% if c.name==model.selected %}style="font-weight:600;background:#f0fff4"{% endif %}>
<td>{{ c.name }}</td><td>{{ '%.4f'|format(c.primary_score) }}</td>
<td>{{ '%.3f'|format(c.cv_mean) }} ± {{ '%.3f'|format(c.cv_std) }}</td>
<td>{{ '%.2f'|format(c.train_seconds) }}</td><td>{{ '%.2f'|format(c.inference_ms_per_1k) }}</td></tr>{% endfor %}
</table><p>Selected: <strong>{{ model.selected }}</strong>.</p></div>{% endif %}

<h2>Validation</h2>
<div class="card"><p>Verdict <span class="{{ validation.verdict }}">{{ validation.verdict|upper }}</span>,
max safe deployment level {{ validation.max_safe_deployment_level }}.</p>
<table><tr><th>Check</th><th>Status</th><th>Detail</th></tr>
{% for c in validation.checks %}<tr><td>{{ c.name }}</td><td class="{{ c.status }}">{{ c.status }}</td><td class="muted">{{ c.detail }}</td></tr>{% endfor %}
</table></div>

<p class="muted">Reproduce with <code>analysis.py</code> / <code>analysis.ipynb</code>; see <code>lineage.json</code> and <code>environment.lock</code>.</p>
</div></body></html>"""

_EVAL = """<!doctype html><html><head><meta charset="utf-8"><title>Evaluation — {{ goal }}</title>
<style>{{ css }}</style></head><body><div class="wrap">
<h1>Model evaluation report</h1><p class="sub">{{ goal }} · {{ model.task }} · metric {{ model.metric }}</p>
<h2>Candidate comparison</h2>
<div class="card"><table><tr><th>Candidate</th><th>Primary ({{ model.metric }})</th><th>All metrics</th><th>CV</th><th>Latency ms/req</th></tr>
{% for c in model.candidates %}<tr {% if c.name==model.selected %}style="font-weight:600;background:#f0fff4"{% endif %}>
<td>{{ c.name }}</td><td>{{ '%.4f'|format(c.primary_score) }}</td>
<td class="muted">{% for k,v in c.metrics.items() %}{{ k }}={{ '%.3f'|format(v) }} {% endfor %}</td>
<td>{{ '%.3f'|format(c.cv_mean) }}±{{ '%.3f'|format(c.cv_std) }}</td>
<td>{{ '%.2f'|format(c.inference_ms_per_1k) }}</td></tr>{% endfor %}</table></div>
{% if finops %}<h2>Cost / quality options</h2>
<div class="card"><table><tr><th>Option</th><th>Candidate</th><th>Score</th><th>Latency</th><th>Est. monthly serving</th></tr>
{% for name, o in finops.options.items() %}<tr><td>{{ name }}</td><td>{{ o.candidate }}</td>
<td>{{ o.validation_score }}</td><td>{{ o.api_latency_ms }} ms</td><td>${{ o.est_monthly_serving_usd }}</td></tr>{% endfor %}
</table><p><strong>Recommendation:</strong> {{ finops.recommendation.choice }} — {{ finops.recommendation.rationale }}</p></div>{% endif %}
<h2>Validation</h2>
<div class="card"><p>Verdict <span class="{{ validation.verdict }}">{{ validation.verdict|upper }}</span>;
max safe deployment level {{ validation.max_safe_deployment_level }}/4.</p></div>
</div></body></html>"""


def executive_html(ctx_data: dict[str, Any]) -> str:
    return _env.from_string(_EXEC).render(css=_BASE_CSS, **ctx_data)


def technical_html(ctx_data: dict[str, Any]) -> str:
    return _env.from_string(_TECH).render(css=_BASE_CSS, **ctx_data)


def evaluation_html(ctx_data: dict[str, Any]) -> str:
    return _env.from_string(_EVAL).render(css=_BASE_CSS, **ctx_data)


def model_card_md(d: dict[str, Any]) -> str:
    m = d["model"]
    lines = [
        f"# Model card — {d['goal']}", "",
        f"- **Mission:** `{d['mission_id']}`",
        f"- **Task:** {m['task']}",
        f"- **Target:** {d.get('target')}",
        f"- **Primary metric:** {m['metric']}",
        f"- **Selected model:** {m['selected']}",
        f"- **Validation verdict:** {d['validation']['verdict'].upper()} "
        f"(max safe deployment level {d['validation']['max_safe_deployment_level']}/4)",
        "", "## Intended use", "",
        d.get("intended_use", "Decision support for the stated goal. Not a substitute for human "
              "judgement on high-stakes decisions."),
        "", "## Performance", "",
        "| Candidate | " + m["metric"] + " | CV mean ± std |",
        "|---|---|---|",
    ]
    for c in m["candidates"]:
        lines.append(f"| {c['name']} | {c['primary_score']:.4f} | {c['cv_mean']:.3f} ± {c['cv_std']:.3f} |")
    lines += ["", "## Training data", "",
              f"- Rows: {m['n_train']} train / {m['n_test']} test",
              f"- Features: {len(m['feature_columns'])}",
              "", "## Limitations & ethical considerations", ""]
    for lim in d.get("limitations", []):
        lines.append(f"- {lim}")
    lines += ["", "## Validation checks", ""]
    for c in d["validation"]["checks"]:
        lines.append(f"- **{c['name']}** — {c['status'].upper()}: {c['detail']}")
    return "\n".join(lines) + "\n"
